version: "2.7"
services:
  backend:
    environment:
      ENVIRONMENT: DEV
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
      
  db:
    image: postgres:13-alpine
    container_name: job009_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=job009pwd
      - POSTGRES_USER=root
      - POSTGRES_DB=job009
      - PGUSER=root
    expose:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 2s
      retries: 20

volumes:
  postgres_data:
